export interface GlossaryEntry {
  term: string;
  fullForm?: string;
  definition: string;
}

export interface GlossaryCategory {
  id: string;
  title: string;
  icon: string;
  entries: GlossaryEntry[];
}

export const glossaryCategories: GlossaryCategory[] = [
  {
    id: "core",
    title: "Core Computer & Infrastructure Terms",
    icon: "💻",
    entries: [
      { term: "Server", definition: "Computer/system that provides services or resources to other systems." },
      { term: "Client", definition: "System that consumes services/resources from a server." },
      { term: "Host", definition: "Physical machine running virtual machines." },
      { term: "Guest", definition: "Virtual machine running on a host." },
      { term: "VM", fullForm: "Virtual Machine", definition: "Software-defined computer running an OS." },
      { term: "OS", fullForm: "Operating System", definition: "Software managing hardware and providing a platform for applications." },
      { term: "CPU", fullForm: "Central Processing Unit", definition: "Executes instructions." },
      { term: "RAM", fullForm: "Random Access Memory", definition: "Temporary working memory." },
      { term: "HDD", fullForm: "Hard Disk Drive", definition: "Magnetic storage device." },
      { term: "SSD", fullForm: "Solid-State Drive", definition: "Flash-based storage device." },
      { term: "NVMe", fullForm: "Non-Volatile Memory Express", definition: "High-speed storage protocol/interface commonly used with SSDs." },
      { term: "NIC", fullForm: "Network Interface Card", definition: "Hardware/virtual adapter used for network communication." },
      { term: "MAC", fullForm: "Media Access Control", definition: "Hardware/link-layer address assigned to a network interface." },
      { term: "BIOS", fullForm: "Basic Input/Output System", definition: "Traditional firmware interface." },
      { term: "UEFI", fullForm: "Unified Extensible Firmware Interface", definition: "Modern firmware interface." },
      { term: "ISO", fullForm: "ISO image", definition: "Disk image commonly used for OS installation." },
      { term: "VMDK", fullForm: "Virtual Machine Disk", definition: "VMware virtual disk format." },
      { term: "Snapshot", definition: "Point-in-time state of a VM." },
    ],
  },
  {
    id: "networking",
    title: "Networking Glossary",
    icon: "🌐",
    entries: [
      { term: "IP Address", definition: "Logical address used to identify a device/interface on an IP network." },
      { term: "IPv4", definition: "32-bit IP addressing system." },
      { term: "IPv6", definition: "128-bit IP addressing system." },
      { term: "Subnet Mask", definition: "Defines which portion of an IPv4 address represents the network and host." },
      { term: "CIDR", fullForm: "Classless Inter-Domain Routing", definition: "Notation such as /24 used to represent subnet masks." },
      { term: "Default Gateway", definition: "Router/interface a host uses to reach other networks." },
      { term: "DNS", fullForm: "Domain Name System", definition: "Translates domain names to IP addresses." },
      { term: "DHCP", fullForm: "Dynamic Host Configuration Protocol", definition: "Automatically assigns IP addresses to clients." },
      { term: "TCP", fullForm: "Transmission Control Protocol", definition: "Reliable, connection-oriented transport protocol." },
      { term: "UDP", fullForm: "User Datagram Protocol", definition: "Fast, connectionless transport protocol." },
      { term: "Port", definition: "Logical endpoint used by network services." },
      { term: "Protocol", definition: "Set of rules governing communication." },
      { term: "Packet", definition: "Unit of data transmitted over a network." },
      { term: "Frame", definition: "Layer-2 data unit." },
      { term: "Routing", definition: "Process of forwarding traffic between networks." },
      { term: "Switch", definition: "Connects devices within a LAN and forwards Ethernet frames." },
      { term: "Router", definition: "Connects different networks and forwards IP packets." },
      { term: "LAN", fullForm: "Local Area Network", definition: "Network covering a small geographic area." },
      { term: "WAN", fullForm: "Wide Area Network", definition: "Network covering a large geographic area." },
      { term: "VLAN", fullForm: "Virtual Local Area Network", definition: "Logical grouping of devices on the same network segment." },
      { term: "NAT", fullForm: "Network Address Translation", definition: "Translates private IP addresses to public IP addresses." },
      { term: "VPN", fullForm: "Virtual Private Network", definition: "Encrypted tunnel for secure remote access." },
      { term: "FQDN", fullForm: "Fully Qualified Domain Name", definition: "Complete domain name including all subdomains and TLD." },
      { term: "Hostname", definition: "Name assigned to a computer/device." },
      { term: "Loopback", definition: "Interface used by a system to communicate with itself (127.0.0.1)." },
      { term: "Broadcast", definition: "Traffic sent to all applicable hosts in a broadcast domain." },
      { term: "Unicast", definition: "One sender to one receiver communication." },
      { term: "Multicast", definition: "One sender to multiple subscribed receivers communication." },
    ],
  },
  {
    id: "windows-server",
    title: "Windows Server Glossary",
    icon: "🧩",
    entries: [
      { term: "Server Role", definition: "Major service/function provided by Windows Server." },
      { term: "Server Feature", definition: "Supporting functionality that can be installed on Windows Server." },
      { term: "Server Core", definition: "Minimal Windows Server installation without the traditional GUI." },
      { term: "PowerShell", definition: "Microsoft's command-line shell and automation framework." },
      { term: "CMD", fullForm: "Windows Command Prompt", definition: "Traditional Windows command-line interface." },
      { term: "SConfig", definition: "Text-based configuration utility commonly used on Server Core." },
      { term: "Service", definition: "Background process that performs a system function." },
      { term: "Daemon", definition: "General Unix/Linux term for a background service." },
      { term: "Process", definition: "Running instance of a program." },
      { term: "Thread", definition: "Execution unit within a process." },
      { term: "Registry", definition: "Windows configuration database." },
      { term: "Event Viewer", definition: "Tool for viewing Windows event logs." },
      { term: "GPO", fullForm: "Group Policy Object", definition: "Collection of Group Policy settings applied to users/computers." },
      { term: "MMC", fullForm: "Microsoft Management Console", definition: "Framework for hosting administrative tools." },
      { term: "RSAT", fullForm: "Remote Server Administration Tools", definition: "Tools for managing Windows Server roles from a client." },
      { term: "WSUS", fullForm: "Windows Server Update Services", definition: "Service for managing Windows updates." },
      { term: "IIS", fullForm: "Internet Information Services", definition: "Microsoft web server for hosting websites and applications." },
      { term: "SMB", fullForm: "Server Message Block", definition: "Windows file/printer sharing protocol." },
      { term: "RDP", fullForm: "Remote Desktop Protocol", definition: "Protocol for remote desktop connections." },
    ],
  },
  {
    id: "active-directory",
    title: "Active Directory Glossary",
    icon: "🏢",
    entries: [
      { term: "AD", fullForm: "Active Directory", definition: "Microsoft directory service for Windows domain networks." },
      { term: "AD DS", fullForm: "Active Directory Domain Services", definition: "Core directory service that stores information about network objects." },
      { term: "Domain", definition: "Logical administrative/security boundary in Active Directory." },
      { term: "Domain Controller", fullForm: "DC", definition: "Server running AD DS that authenticates and manages domain information." },
      { term: "Forest", definition: "Highest-level AD logical structure containing one or more domains." },
      { term: "Tree", definition: "Collection of related AD domains sharing a contiguous namespace." },
      { term: "OU", fullForm: "Organizational Unit", definition: "Container within AD for organizing objects and applying Group Policy." },
      { term: "User Account", definition: "Identity representing a person/service." },
      { term: "Security Group", definition: "Group used to assign permissions/access." },
      { term: "Computer Account", definition: "AD object representing a domain-joined computer." },
      { term: "Domain Join", definition: "Process of adding a computer to an AD domain." },
      { term: "Authentication", definition: "Verifying who someone/something is." },
      { term: "Authorization", definition: "Determining what an authenticated identity is allowed to do." },
      { term: "Kerberos", definition: "Primary authentication protocol used by modern Active Directory." },
      { term: "LDAP", fullForm: "Lightweight Directory Access Protocol", definition: "Protocol for accessing and maintaining directory information." },
      { term: "NTLM", definition: "Older Windows authentication protocol." },
      { term: "KDC", fullForm: "Key Distribution Center", definition: "Service that issues Kerberos tickets." },
      { term: "SPN", fullForm: "Service Principal Name", definition: "Unique identifier for a service instance in AD." },
      { term: "ACL", fullForm: "Access Control List", definition: "List of permissions attached to an object." },
      { term: "ACE", fullForm: "Access Control Entry", definition: "Individual entry in an ACL." },
      { term: "SID", fullForm: "Security Identifier", definition: "Unique value identifying a user, group, or computer account." },
      { term: "RID", fullForm: "Relative Identifier", definition: "Portion of the SID that identifies the account relative to the domain." },
      { term: "SYSVOL", definition: "Shared directory containing domain-related files such as Group Policy files." },
      { term: "FSMO", fullForm: "Flexible Single Master Operations", definition: "Specialized AD roles for specific operations." },
      { term: "GC", fullForm: "Global Catalog", definition: "Partial read-only copy of all objects in an AD forest." },
    ],
  },
  {
    id: "security",
    title: "Security Glossary",
    icon: "🔐",
    entries: [
      { term: "Authentication", definition: "Proving identity." },
      { term: "Authorization", definition: "Determining permissions." },
      { term: "Accounting/Auditing", definition: "Recording activity." },
      { term: "ACL", fullForm: "Access Control List", definition: "Defines who/what has access to a resource." },
      { term: "Permission", definition: "An allowed or denied action." },
      { term: "Privilege", definition: "Special system-level right." },
      { term: "Least Privilege", definition: "Give only the access necessary." },
      { term: "Encryption", definition: "Converting data into protected form." },
      { term: "Hash", definition: "One-way mathematical representation of data." },
      { term: "Certificate", definition: "Digital credential used to establish identity/trust." },
      { term: "PKI", fullForm: "Public Key Infrastructure", definition: "Framework for managing digital certificates." },
      { term: "TLS", fullForm: "Transport Layer Security", definition: "Cryptographic protocol for secure communications." },
      { term: "Firewall", definition: "Controls network traffic based on rules." },
      { term: "Patch", definition: "Software update fixing bugs/security issues." },
      { term: "Vulnerability", definition: "Weakness that could be exploited." },
      { term: "Exploit", definition: "Technique/code used to take advantage of a vulnerability." },
    ],
  },
];
